version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      tauri:
        patterns: [ 'tauri', 'tauri-build' ]
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/vrc-get-gui"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    groups:
      radix-ui:
        patterns: [ "@radix-ui/*" ]
      react:
        patterns: [ "react", "react-dom", "@types/react", "@types/react-dom" ]
      tanstack-router:
        patterns: [ "@tanstack/*router*" ]
      tailwindcss:
        patterns: [ "tailwindcss", "@tailwindcss/*" ]
